### ISSUE TITLE
Enable warm start

### ISSUE THREAD

**Issue by glennmoy** [baggepinnen/Hyperopt.jl#23]
Just making a note of this for now but I would like to return to it in the future. Being able to restart a hyperopt job is pretty useful and I think the package would benefit from such a feature. 

Perhaps we could achieve this by passing the `Hyperoptimizer ` to `@hyperopt` initiation and it could infer where to resume the search?

**Comment by chriselrod** [comment]
Any updates on this?

**Comment by baggepinnen** [comment]
Unfortunately not, this is a rather slow-moving package nowadays, I haven't made much use of it lately.

If the optimizer is run with the iteration interface, it should be straightforward to restart it by simply performing more iterations, but I haven't verified it. The Readme shows how to use the iteration interface should anyone want to try it out.

**Comment by glennmoy** [comment]
I'll note that I haven't made use of the package for some time and don't expect to need this personally in the future. But I will leave the issue open in case it serves others.

**Comment by baggepinnen** [comment]
This feature is now implemented thanks to @norci 
Just supply an existing hyperoptimizer as the second argument to `@hyperopt`
Example: https://github.com/baggepinnen/Hyperopt.jl/blob/3fc03e42337e7d328886ae4a6099a1b269b6176c/test/runtests.jl#L30
