### ISSUE TITLE
Choose sampler when using Hyperoptimizer not macro @hyperopt

### ISSUE THREAD

**Issue by luboshanus** [baggepinnen/Hyperopt.jl#30]
I got an error when trying to put `RandomSampler()` into function Hyperoptimizer. I prefer this function to `@hyperopt` macro because I do run script and I did not figure out a way how to save my loss from `@hyperopt` and parameters into `ho` to have results.

Into this code, how do I put sampler.
```
ho = Hyperoptimizer(10, a = LinRange(1,2), b = [true, false], c = randn(100))
for (i,a,b,c) in ho
    res = computations(a,b,c)
    push!(ho.results, res)
    push!(ho.history, [a,b,c])
end
```

If I put it into `Hyperoptimizer(10, sampler=RandomSampler(), ... )` I got error:
```
ERROR: MethodError: no method matching length(::RandomSampler)
Closest candidates are:
  length(::Core.SimpleVector) at essentials.jl:597
  length(::Base.MethodList) at reflection.jl:819
  length(::Core.MethodTable) at reflection.jl:893
  ...
Stacktrace:
 [1] (::getfield(Hyperopt, Symbol("##4#5")))(::RandomSampler) at ./none:0
...
```

Also a solution could be to answer: How do I save results of one run of sampler into `ho` when using macro `@hyperopt` without using macro `@show result, params`.

Thank you a lot.

**Comment by baggepinnen** [comment]
Thanks for the issue. I have pushed a change that allows you to call (without keyword argument for sampler)
```julia
Hyperoptimizer(10, RandomSampler(), ... )
```

I'm not sure what you mean with your second point, when using the `@hyperopt` macro, the results are automatically stored in the `ho` object. After running the code below
```julia
ho = @hyperopt for i=10, a=1:5
    f(a)
end
```
`ho` will contain `f(a)` for all the sampled `a`. They will be stored in `ho.results` and the sampled parameters will be stored in `ho.history`.
