### ISSUE TITLE
Generate named tuples as hyperopt iteration elements?

### ISSUE THREAD

**Issue by mchitre** [baggepinnen/Hyperopt.jl#42]
It would be nice if the `Hyperoptimizer` generated named tuples, since it already has information about the names of the hyper parameters. These could still be accessed using index and so would maintain backward compatibility. But it would allow better readability and extensibility with named indexing, if the `Hyperoptimizer` was used as a generic iterator.

Example:
```julia
buildmodel(θ) = somemodel(θ.a, θ.b, θ.c)

for θ ∈ Hyperoptimizer(10, λ=exp10.(LinRange(-5,-1,9)), a = LinRange(1,2,50), b = [true, false], c = randn(100))
  model = buildmodel(θ)
  train!(model, data, ADAM(θ.λ))
end
```

**Comment by baggepinnen** [comment]
Thanks for the idea, a new release with this supported should be out within a few hours :+1:
