### ISSUE TITLE
Feature request: Allow customization of `pmap` arguments

### ISSUE THREAD

**Issue by ericphanson** [baggepinnen/Hyperopt.jl#59]
Right now, it's set as https://github.com/baggepinnen/Hyperopt.jl/blob/a7026b38bd4d4960c22aeff864fe0e45bdefa68d/src/Hyperopt.jl#L160-L165

Unfortunately for me, I need to pass things like `on_error`, due to crashes on my workers.

**Comment by omus** [comment]
You could pass in arguments and keywords to `$(pmap)` if you could pass in a custom `pmap` function. However, I don't believe there is support for this via `@phyperopt`

**Comment by baggepinnen** [comment]
The easiest way of doing this right now might be to define your own macro `@my_phyperopt` that sends in the custom `pmap` function like how it's done here https://github.com/baggepinnen/Hyperopt.jl/blob/a7026b38bd4d4960c22aeff864fe0e45bdefa68d/src/Hyperopt.jl#L190 I'm not sure how to add this functionality to the original macro without making the expression parsing in the macro much more complicated, suggestions are welcome :)

**Comment by baggepinnen** [comment]
Actually, macros can take more than one argument, perhaps all but the first argument are sent as options to `pmap`? Unfortunately, macros can't take keyword arguments, but perhaps a named tuple?

**Comment by ericphanson** [comment]
Passing keyword arguments as a NamedTuple sounds good to me!
