### ISSUE TITLE
BOHB: combination of Bayesian optimization and Hyperband

### ISSUE THREAD

**Issue by torfjelde** [baggepinnen/Hyperopt.jl#6]
[BOHB: Robust and Efficient Hyperparameter Optimization at Scale](https://arxiv.org/abs/1807.01774v1) shows very nice empirical results compared to Hyperband. Would be awesome to have BOHB available in Hyperopt.jl!

I'd love to eventually attempt an implementation of this myself, but figured I'd add it as an issue in case anyone wants to have a go at it before I find the time:)

**Comment by noil-reed** [comment]
I'm managing to implement that.

**Comment by baggepinnen** [comment]
Anyone interested, feel free to help out review #54 🎉

**Comment by baggepinnen** [comment]
This is now available thanks to @noilreed 😃
