### ISSUE TITLE
What is the first argument in the loop

### ISSUE THREAD

**Issue by KronosTheLate** [baggepinnen/Hyperopt.jl#75]
A comment from an example in the readme states: "The first argument to the for loop is always interpreted as the number of iterations".

But later on, in the hyperband examples, instead of `i`, the first argument to the loop gets the variable name `resources`, indicating that it is no longer a count. Indeed, in the loop, it takes on non-integer values. Does this not mean that the quoted statement is incorrect?

Furthermore, I am confused about the meaning of the first loop argument during hyperopt. What is `resources` measured in? Is it some sort of time-budget? For the first part, the last part, or the total process?

This issue is not created to get an answer here. Rather, consider it a part of my experience in understanding this package which I consider an issue.

**Comment by baggepinnen** [comment]
> Does this not mean that the quoted statement is incorrect?

yes, it does not hold for hyperband

> What is resources measured in? Is it some sort of time-budget?

It's whatever you want it to be, maximum time, number of iterations etc. That's why it's called resources, a generic word to mean anything that controls the amount of computational effort.
