### ISSUE TITLE
Redefining parameter space during hyperband with RandomSampler()

### ISSUE THREAD

**Issue by KronosTheLate** [baggepinnen/Hyperopt.jl#76]
With the following setting for the loop
```
hohb = @hyperopt for resources=20,
        sampler=Hyperband(R=η^n_reductions; η, inner=RandomSampler()),
       #my parameters come here
```
, I sample a number of neural networks. Each time I sample a new one, it gets an ID. The ID is found as the number of networks sampled thus far + 1. I found a peculiar artifact in the result - it seems as if the average performance goes up with higher ID:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/61620837/162910051-990b35c5-b360-4f96-b134-8f759654c227.png">
<img width="511" alt="image" src="https://user-images.githubusercontent.com/61620837/162910096-599606f4-2237-4a54-a01e-86db22ffa905.png">

So it seems to me like the sampling is not random within the same parameter space during the entire process, but that somehow the previously sampled and tested parameters influence the parameter-space of the new samples. 

This is awesome, and clearly a feature, not a bug. But I had no idea this was going on from the `readme` file. So first of all, I would like for this to be documented.

Secondly, I am curious - what are the exact rules for the redefinition of the sample-space during the loop?

**Comment by baggepinnen** [comment]
This is not an artifact, it's fundamentally how hyperband works. I would suggest reading the hyperband paper (linked in the readme) if you want to understand how the method works. If you want random sampling, I suggest the `RandomSampler`.

**Comment by KronosTheLate** [comment]
I was confused on 2 points in writing my post:

1) The increase in performance with larger ID comes from the larger initial resource allocation, NOT a change in parameter space
2) I was completely oblivious to the second part of hyperband, which explores the "n vs B/n" tradeoff as they call it. Thanks for promoting me to read it more closely.

And that closes this issue. Thanks.
