### ISSUE TITLE
Brute-force search

### ISSUE THREAD

**Issue by MohHizzani** [baggepinnen/Hyperopt.jl#90]
I'm using Random Sampler, and thought if gave the number of iteration equal to the length of brute-force size, it would do it automatically. However, I noticed that the sampler is wasting iterations by repeating tests already did.

How can I make it perform brute-force search when # of iters >= total length of product of hyper-parameters? (i.e. draw without replacement)

**Comment by baggepinnen** [comment]
There is currently no option to perform such search. To search a pre-selected set of parameters, you could just iterate over all of them and do not really need this package?

In general, the objective function may be stochastic, and then there is merit to repeated searches using the random sampler. The choice of not including grid search for continuous parameters is deliberate, it's an extremely poor optimizer.
