### ISSUE TITLE
Merge into MLJTuning.jl?

### ISSUE THREAD

**Issue by ParadaCarleton** [baggepinnen/Hyperopt.jl#97]
From what I can tell, this package seems to combine a handful of implementations of optimization methods with an interface for optimization. Would it make sense to:
1. Merge any features in this package missing from MLJTuning.jl into MLJTuning, and
2. Separate the optimization methods into a different package?

**Comment by baggepinnen** [comment]
1. As far as I know, the MLJ packages really only work with MLJ. I am not interested in using MLJ so it makes little sense work on any such integration.
2. Maybe, but the "interface" provided by this package is extremely lightweight, so I'm not sure what benefit there would be from doing this?

**Comment by baggepinnen** [comment]
I'll close the issue since it's more of a discussion, but feel free to continue the discussion if you'd like

**Comment by ParadaCarleton** [comment]
> * As far as I know, the MLJ packages really only work with MLJ. I am not interested in using MLJ so it makes little sense work on any such integration.

MLJTuning.jl is a standardized interface for hyperparameter tuning; adding MLJTuning support would let you use the methods in this package to tune basically any ML model in the Julia ecosystem, since almost all ML packages in Julia provide an MLJ interface.

**Comment by baggepinnen** [comment]
This discussion is better held in this existing issue
https://github.com/JuliaAI/MLJTuning.jl/issues/55
